#!/bin/bash

osascript << EOF
set targetBuddyPhone to text returned of (display dialog "enter phone number" default answer "")
set targetMessage to text returned of (display dialog "enter message"  default answer "")
tell application "Messages"
  set targetService to 1st service whose service type = iMessage
  set targetBuddy to buddy targetBuddyPhone of targetService
  send targetMessage to targetBuddy
end tell
EOF