#!/bin/bash

list=()
num=()
echo "enter length"
read length
echo "enter width"
read width

printf '\e[8;%s;%st' "$length" "$width"

for ((i=0;i<$width;i++)); do
  num[$i]=$(($RANDOM % $length))
  for ((j=0;j<$length;j++)); do
    if (( $((${num[$i]}-$j)) <= 0 )); then
      list[$j]+=" "
    else
      list[$j]+="█"
    fi
  done
done

clear

for ((i=0;i<$length;i++)); do
  echo "${list[$i]}"
done